### ISSUE TITLE
这个插件不更新了么？

### ISSUE THREAD

**Issue by abramstyle** [ricky-ru/fis-parser-stylus#1]
我在fis中用fis-parser-sylus出现了一些问题，不管怎么写都会在import其他文件时报错failed to locate @import file import/helper.styl [stylus]

**Comment by xjchenhao** [comment]
@abramstyle  你好，这个问题解决了吗？我也遇到了这个问题。

**Comment by xjchenhao** [comment]
[ERROR] parser.stylus: stylus:1:9
   1| @import 'qst/all'
--------------^
   2| $global-reset();
   3| $viewsize();
   4|

failed to locate @import file qst/all.styl [stylus]

**Comment by abramstyle** [comment]
@xjchenhao 因为我们项目是新项目，所以我改用sass了，这个问题也就不了了之了，抱歉

**Comment by xjchenhao** [comment]
@abramstyle 好吧，只能请作者解决了。@luyujun

**Comment by ricky-ru** [comment]
@xjchenhao ，目前我不用stylus了，用sass了。

**Comment by xjchenhao** [comment]
@luyujun ，stylus不好用吗，为什么放弃它了？
